spring.application.name=pennywise
server.port=8090

# PostgreSQL DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/pennywise
spring.datasource.username=pennyuser
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Dialect for PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Show SQL queries (optional, for debugging)
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Automatically create/update DB schema (good for dev)
spring.jpa.hibernate.ddl-auto=update

# oauth Authencation
spring:
security:
oauth2:
resourceserver:
jwt:
issuer-uri: https://your-auth-server.com/issuer

